enum errorType {
    NAME_OR_PASSWORD_IS_REQUIRED = 'NAME_OR_PASSWORD_IS_REQUIRED',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    NO_SUCH_USER = 'NO_SUCH_USER',
    USER_OR_PASSWORD_INCONSISTENT = 'USER_OR_PASSWORD_INCONSISTENT',
    UNAUTHORIZATION = 'UNAUTHORIZATION',
    CONFLICT='CONFLICT'
}

export default errorType